@startuml
!theme mars

scale 1000 width
left to right direction

actor "User" as user
rectangle "Data Preprocessing Tool" {
  usecase "Upload CSV File" as UC1
  usecase "Setup Operations" as UC2
  usecase "Add Node Representing an Operation" as UC2_1
  usecase "Set the Input of Operation Node" as UC2_2
  usecase "Set Node Parameters" as UC2_3
  usecase "Display Node Data Frame" as UC5
  usecase "Save Node Data Frame as a CSV File" as UC6
  usecase "Switch the Application Language" as UC7
}
user --> UC1
user --> UC2
user --> UC5
user --> UC6
user --> UC7
UC2 ..> UC2_1 : <<includes>>
UC2 ..> UC2_2 : <<includes>>
UC2 ..> UC2_3 : <<includes>>
@enduml